version: "3.1"

services:
  pingdatasync:
    image: pingidentity/pingdatasync:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-playground.git
      - SERVER_PROFILE_PATH=pingone-cloud/pingdatasync-pingonecloud
      ##################################################################################################
      # Replace the Variables below with the Microsoft Graph API and App Registration Details
      ##################################################################################################
      - MS_AZURE_TENANT_ID=
      - MS_AZURE_APP_REGISTRATION_CLIENT_ID=
      - MS_AZURE_APP_REGISTRATION_CLIENT_SECRET=
      ##################################################################################################
      # Replace the Variables below with the PingOne for Customer Details
      ##################################################################################################
      - PING_ONE_ENVIRONMENT_ID=
      - PING_ONE_POPULATION_ID=
      - PING_ONE_CLIENT_ID=
      - PING_ONE_CLIENT_SECRET=
      - VERBOSE=false
    ports:
      - 2636:636
      - 2443:443
    networks:
      - pingnet
  
  pingdataconsole:
    image: pingidentity/pingdataconsole
    ports:
      - 8080:8080
    networks: 
      - pingnet  
              
networks:
    pingnet:

