#!/usr/bin/env sh
THIS=`basename ${0}`
CMD="${1}"

PROPS_FILE="${HOME}/.pingidentity/austin.properties"

test ! -f "${PROPS_FILE}" && ./configure
test -z "${DEVOPS_OUT_BASE}" && . "${PROPS_FILE}"

################################################################################
# Print usage information
################################################################################
function usage()
{
cat <<EO_USAGE

Usage: ${THIS}

Examples

    ${THIS}

EO_USAGE

  exit
}

test -z "${DEVOPS_OUT_BASE}" && exit

echo "
################################################################################
# This will archive the '${DEVOPS_OUT_BASE}' directory and
# and recreate a new set of directories.
#
#    Archive Directory: ${DEVOPS_OUT_BASE}.$$
################################################################################
"

test   -d "${DEVOPS_OUT_BASE}" && mv "${DEVOPS_OUT_BASE}" "${DEVOPS_OUT_BASE}.$$"

mkdir -p "${DEVOPS_OUT_BASE}/lab01/pingdirectory"
mkdir -p "${DEVOPS_OUT_BASE}/lab02"
mkdir -p "${DEVOPS_OUT_BASE}/lab03"
mkdir -p "${DEVOPS_OUT_BASE}/lab04"
mkdir -p "${DEVOPS_OUT_BASE}/lab05"
mkdir -p "${DEVOPS_OUT_BASE}/lab06"
