#!/usr/bin/env sh
THIS=`basename ${0}`
CMD="${1}"

PROPS_FILE="${HOME}/.pingidentity/austin.properties"

test ! -f "${PROPS_FILE}" && ./configure

################################################################################
# Print usage information
################################################################################
function usage()
{
cat <<EO_USAGE

Usage: ${THIS}

Examples

    ${THIS}

EO_USAGE

  exit
}

echo "
################################################################################
# This will archive the '${DEVOPS_IN_BASE}' directory and
# and recreate a new set of directories.
#
#    Archive Directory: ${DEVOPS_IN_BASE}.$$
################################################################################
"

test ! -d "${DEVOPS_IN_BASE}"  && echo "No local DEVOPS_IN_BASE  base found: ${DEVOPS_IN_BASE}"

test   -d "${DEVOPS_IN_BASE}" && mv "${DEVOPS_IN_BASE}" "${DEVOPS_IN_BASE}.$$"

mkdir -p "${DEVOPS_IN_BASE}/lab01/pingdirectory"
mkdir -p "${DEVOPS_IN_BASE}/lab02"
mkdir -p "${DEVOPS_IN_BASE}/lab03"
mkdir -p "${DEVOPS_IN_BASE}/lab04"
mkdir -p "${DEVOPS_IN_BASE}/lab05"
mkdir -p "${DEVOPS_IN_BASE}/lab06"
